# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fef6fc6142116c1eaac9c63ee78f1b3bffa9eb4e3ca8d5d37a638155e687ffff13a832be74e1b0d600b45164763d5df8e0a210fc4c2c5acf303fac2132e0484

test:
  secret_key_base: bc09ed259891a3d370662c28756cedc6a25db63c38441db43722996b43f0b2ca65e3a4aef6e5d4bab3fa24a3e4c7b65b929cb38756cd47d3803261e9ffdea208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
